### ISSUE TITLE
Idea: self-hosted comments section for blog posts

### ISSUE THREAD

**Issue by stamminator** [PiranhaCMS/piranha.modules#1]
I don't have an immediate need for something like this, just seeing if this is a viable idea for a module. It would be a comments section that would go at the bottom of blog post pages. It would still feature OAuth logins for services like Facebook, Twitter, Github, etc., but could differ from something like Disqus in the following ways:

1. All of its data (comments, users, reactions, etc.) would live in the same database that the rest of Piranha uses instead of relying on an external service.
2. Much lighter weight, offering faster load times over Disqus, which often takes a very long time to load on sites.
3. Simpler admin system that isn't so complicated to use
4. NO ADS!

I don't know if it would be better to build this from scratch or to build a wrapper around an existing solution, but it's an idea.

**Comment by tidyui** [comment]
Hi @stamminator! Native comments were added in version 8.1 😁

**Comment by stamminator** [comment]
Whoops, my bad! And well done!
