### ISSUE TITLE
Module for editing text files & a separate package for having dynamicly-generated CSS files from SCSS files editable via the first package

### ISSUE THREAD

**Issue by 121GWJolt** [PiranhaCMS/piranha.modules#5]
Need to make this functionality for something I'm working on. Essentially, one package will generally allow embedding a text editor on supported documents, and then a separate component that can hook into SCSS ones and compile them for use in the pages/posts. The end result is a "skin" system for pages!

Have some basic ideas on how I want it to work and I'm planning on starting it but want to see if anyone's attempted this or would want to work on it, or would at least be willing to rubber-duck me.

Am probably gonna start my efforts in a week if something doesn't exist.

**Comment by tidyui** [comment]
I think the easiest solution would be to add support for uploading scss and css files to the media library (https://piranhacms.org/docs/master/content/media).

Then create a separate view in the manager that lists scss files in the media library, and when saved compiles them and updates the outputted css in the library.

/ Regards

**Comment by 121GWJolt** [comment]
Yep, that's sort of what I was thinking about! Might also try and see if I can save two different outputted CSS: one for draft pages to pull, and one for published pages.

Planning on separating the text editor component (at least eventually) to make it possible to pull into other things and allow people to edit other kinds of docs.
